---
# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      TRUSTED_PROXIES: '127.0.0.1,REMOTE_ADDR'
      TRUSTED_HOSTS: '^casino\.gallotta\.fr$'